const en = {
  metadata: { title: 'JobTracker', description: 'Track your job applications and interviews' },
  common: { save: 'Save', cancel: 'Cancel', delete: 'Delete', close: 'Close', edit: 'Edit', create: 'Create', loading: 'Loading…', tryAgain: 'Try again', search: 'Search…', settings: 'Settings', language: 'Language', noResults: 'No results found' },
  navigation: { dashboard: 'Dashboard', applications: 'All Applications', findJobs: 'Find Jobs', wishlist: 'Wishlist', calendar: 'Calendar', companies: 'Companies', contacts: 'Contacts', notes: 'Notes', reminders: 'Reminders', notifications: 'Notifications', statistics: 'Statistics', profile: 'Profile', vacancies: 'Vacancies', candidates: 'Candidates', management: 'Management', workspace: 'Workspace', analytics: 'Analytics', settings: 'Settings' },
  topbar: { profileSettings: 'Profile Settings', settings: 'Settings', logout: 'Logout', notifications: 'Notifications', avatar: 'Avatar' },
  public: { browseJobs: 'Browse Jobs', myApplications: 'My Applications', dashboard: 'Dashboard', signIn: 'Sign In', signUp: 'Sign Up', browseTitle: 'Browse Jobs' },
  jobs: { search: 'Search jobs…', location: 'Filter by location…', searchButton: 'Search', empty: 'No job vacancies found. Try adjusting your search filters.', posted: 'Posted {date}', previous: 'Previous', next: 'Next', loadFailed: 'Failed to load job vacancies', notAvailable: 'N/A' },
  vacancies: { active: 'Active', archived: 'Archived', search: 'Search title or company', allStatuses: 'All statuses', published: 'Published', closed: 'Closed', noMatch: 'No vacancies match these filters.', empty: 'No vacancies yet. Create your first vacancy to get started.', created: 'Created {date}', deleted: 'Vacancy deleted successfully.', updated: 'Vacancy status updated successfully.', deleteFailed: 'Failed to delete vacancy.', updateFailed: 'Failed to update vacancy status.', loadFailed: 'Failed to load vacancies' },
  language: { label: 'Language', description: 'Choose the language used throughout JobTracker.', detected: 'The initial language is selected from your browser settings.', english: 'English', polish: 'Polski', russian: 'Русский', changed: 'Language changed', failed: 'Failed to change language' },
  documents: { securePreview: 'Secure document preview', download: 'Download', open: 'Open document in new tab', close: 'Close preview', unavailable: 'Preview unavailable', fallback: 'You can still download the original document.', loadFailed: 'Failed to load document preview' },
  notifications: { loading: 'Loading notifications…', loadError: 'Error loading notifications: {error}', all: 'All', unread: 'Unread ({count})', read: 'Read', markAll: 'Mark all as read', noUnread: 'No unread notifications', empty: 'No notifications', emptyYet: 'No notifications yet', alreadyRead: 'Already read', markRead: 'Mark as read', delete: 'Delete', viewAll: 'View all notifications', title: 'Notifications' },
  auth: { tagline: 'Track your job journey', join: 'Join us today', welcome: 'Welcome back', signInAccount: 'Sign in to your account', createAccount: 'Create an account', createYourAccount: 'Create your account', terms: 'By signing in, you agree to our Terms of Service', loginFailed: 'Login failed', loginRetry: 'Login failed. Please try again.', unexpected: 'Something went wrong. Please try again.', signIn: 'Sign in', email: 'Email address', password: 'Password', noAccount: "Don't have an account?", newHere: 'New here?', alreadyAccount: 'Already have an account?', register: 'Create account', firstName: 'First name', lastName: 'Last name', confirmPassword: 'Confirm password', back: 'Back', who: 'Who are you?', seeker: 'Job Seeker', seekerDescription: 'Looking for new opportunities', recruiter: 'Recruiter', recruiterDescription: 'Hiring great talent', asRole: 'As a {role}', fillFields: 'Please fill in all fields', passwordRequirements: 'Password does not meet requirements', passwordsMatch: 'Passwords match', passwordsMismatch: 'Passwords do not match', atLeastEight: 'At least 8 characters', uppercase: 'One uppercase letter', lowercase: 'One lowercase letter', number: 'One number', registrationFailed: 'Registration failed', registrationRetry: 'Registration failed. Please try again.' },
  pages: { settingsTitle: 'Settings', settingsDescription: 'Manage your application preferences.', profileTitle: 'Profile', profileDescription: 'Manage your account settings and information', applicationsTitle: 'My Applications', applicationsDescription: 'Track and manage your job applications', companiesTitle: 'Companies', companiesDescription: 'Keep a private list of companies you follow.', contactsTitle: 'Contacts', contactsDescription: 'Manage people you meet during your job search.', notesTitle: 'Notes', notesDescription: 'Keep private notes connected to your applications.', remindersTitle: 'Reminders', remindersDescription: 'Plan follow-ups and important application deadlines.', calendarTitle: 'Calendar', calendarDescription: 'Keep track of interviews and personal events', statisticsTitle: 'Statistics', vacanciesTitle: 'Vacancies', vacanciesDescription: 'Create and manage your job vacancies', createVacancy: 'Create Vacancy', candidatesTitle: 'Candidates', candidatesDescription: 'View all candidates who applied to your vacancies', notificationsTitle: 'Notifications', notificationsDescription: 'Stay updated with your application status', wishlistTitle: 'Wishlist', wishlistDescription: 'Your saved job opportunities' }
} as const;
export default en;
