import type en from './en';
type Messages = { [K in keyof typeof en]: { [P in keyof (typeof en)[K]]: string } };
const pl: Messages = {
  metadata: { title: 'JobTracker', description: 'Śledź swoje aplikacje o pracę i rozmowy kwalifikacyjne' },
  common: { save: 'Zapisz', cancel: 'Anuluj', delete: 'Usuń', close: 'Zamknij', edit: 'Edytuj', create: 'Utwórz', loading: 'Ładowanie…', tryAgain: 'Spróbuj ponownie', search: 'Szukaj…', settings: 'Ustawienia', language: 'Język', noResults: 'Brak wyników' },
  navigation: { dashboard: 'Panel', applications: 'Wszystkie aplikacje', findJobs: 'Znajdź pracę', wishlist: 'Ulubione', calendar: 'Kalendarz', companies: 'Firmy', contacts: 'Kontakty', notes: 'Notatki', reminders: 'Przypomnienia', notifications: 'Powiadomienia', statistics: 'Statystyki', profile: 'Profil', vacancies: 'Oferty pracy', candidates: 'Kandydaci', management: 'Zarządzanie', workspace: 'Organizacja', analytics: 'Analityka', settings: 'Ustawienia' },
  topbar: { profileSettings: 'Ustawienia profilu', settings: 'Ustawienia', logout: 'Wyloguj', notifications: 'Powiadomienia', avatar: 'Awatar' },
  public: { browseJobs: 'Przeglądaj oferty', myApplications: 'Moje aplikacje', dashboard: 'Panel', signIn: 'Zaloguj się', signUp: 'Zarejestruj się', browseTitle: 'Przeglądaj oferty pracy' },
  jobs: { search: 'Szukaj ofert…', location: 'Filtruj według lokalizacji…', searchButton: 'Szukaj', empty: 'Nie znaleziono ofert. Zmień kryteria wyszukiwania.', posted: 'Opublikowano {date}', previous: 'Poprzednia', next: 'Następna', loadFailed: 'Nie udało się wczytać ofert pracy', notAvailable: 'Brak' },
  vacancies: { active: 'Aktywne', archived: 'Archiwalne', search: 'Szukaj po nazwie lub firmie', allStatuses: 'Wszystkie statusy', published: 'Opublikowana', closed: 'Zamknięta', noMatch: 'Brak ofert pasujących do filtrów.', empty: 'Brak ofert. Utwórz pierwszą ofertę pracy.', created: 'Utworzono {date}', deleted: 'Oferta została usunięta.', updated: 'Status oferty został zmieniony.', deleteFailed: 'Nie udało się usunąć oferty.', updateFailed: 'Nie udało się zmienić statusu.', loadFailed: 'Nie udało się wczytać ofert' },
  language: { label: 'Język', description: 'Wybierz język używany w całym JobTracker.', detected: 'Początkowy język jest wybierany na podstawie ustawień przeglądarki.', english: 'English', polish: 'Polski', russian: 'Русский', changed: 'Zmieniono język', failed: 'Nie udało się zmienić języka' },
  documents: { securePreview: 'Bezpieczny podgląd dokumentu', download: 'Pobierz', open: 'Otwórz dokument w nowej karcie', close: 'Zamknij podgląd', unavailable: 'Podgląd niedostępny', fallback: 'Nadal możesz pobrać oryginalny dokument.', loadFailed: 'Nie udało się wczytać podglądu dokumentu' },
  notifications: { loading: 'Ładowanie powiadomień…', loadError: 'Błąd ładowania powiadomień: {error}', all: 'Wszystkie', unread: 'Nieprzeczytane ({count})', read: 'Przeczytane', markAll: 'Oznacz wszystkie jako przeczytane', noUnread: 'Brak nieprzeczytanych powiadomień', empty: 'Brak powiadomień', emptyYet: 'Nie masz jeszcze powiadomień', alreadyRead: 'Przeczytane', markRead: 'Oznacz jako przeczytane', delete: 'Usuń', viewAll: 'Zobacz wszystkie powiadomienia', title: 'Powiadomienia' },
  auth: { tagline: 'Śledź swoją drogę zawodową', join: 'Dołącz do nas', welcome: 'Witaj ponownie', signInAccount: 'Zaloguj się na swoje konto', createAccount: 'Utwórz konto', createYourAccount: 'Utwórz swoje konto', terms: 'Logując się, akceptujesz Warunki korzystania z usługi', loginFailed: 'Logowanie nie powiodło się', loginRetry: 'Logowanie nie powiodło się. Spróbuj ponownie.', unexpected: 'Coś poszło nie tak. Spróbuj ponownie.', signIn: 'Zaloguj się', email: 'Adres e-mail', password: 'Hasło', noAccount: 'Nie masz konta?', newHere: 'Jesteś tu pierwszy raz?', alreadyAccount: 'Masz już konto?', register: 'Utwórz konto', firstName: 'Imię', lastName: 'Nazwisko', confirmPassword: 'Potwierdź hasło', back: 'Wstecz', who: 'Kim jesteś?', seeker: 'Osoba szukająca pracy', seekerDescription: 'Szukam nowych możliwości', recruiter: 'Rekruter', recruiterDescription: 'Zatrudniam utalentowane osoby', asRole: 'Jako: {role}', fillFields: 'Wypełnij wszystkie pola', passwordRequirements: 'Hasło nie spełnia wymagań', passwordsMatch: 'Hasła są zgodne', passwordsMismatch: 'Hasła nie są zgodne', atLeastEight: 'Co najmniej 8 znaków', uppercase: 'Jedna wielka litera', lowercase: 'Jedna mała litera', number: 'Jedna cyfra', registrationFailed: 'Rejestracja nie powiodła się', registrationRetry: 'Rejestracja nie powiodła się. Spróbuj ponownie.' },
  pages: { settingsTitle: 'Ustawienia', settingsDescription: 'Zarządzaj preferencjami aplikacji.', profileTitle: 'Profil', profileDescription: 'Zarządzaj kontem i informacjami', applicationsTitle: 'Moje aplikacje', applicationsDescription: 'Śledź swoje aplikacje o pracę', companiesTitle: 'Firmy', companiesDescription: 'Prowadź prywatną listę obserwowanych firm.', contactsTitle: 'Kontakty', contactsDescription: 'Zarządzaj osobami poznanymi podczas poszukiwania pracy.', notesTitle: 'Notatki', notesDescription: 'Prowadź prywatne notatki powiązane z aplikacjami.', remindersTitle: 'Przypomnienia', remindersDescription: 'Planuj kolejne kroki i ważne terminy.', calendarTitle: 'Kalendarz', calendarDescription: 'Śledź rozmowy i osobiste wydarzenia', statisticsTitle: 'Statystyki', vacanciesTitle: 'Oferty pracy', vacanciesDescription: 'Twórz i zarządzaj ofertami pracy', createVacancy: 'Utwórz ofertę', candidatesTitle: 'Kandydaci', candidatesDescription: 'Przeglądaj kandydatów na swoje oferty', notificationsTitle: 'Powiadomienia', notificationsDescription: 'Śledź zmiany statusu aplikacji', wishlistTitle: 'Ulubione', wishlistDescription: 'Zapisane oferty pracy' }
};
export default pl;
