import type en from './en';
type Messages = { [K in keyof typeof en]: { [P in keyof (typeof en)[K]]: string } };
const ru: Messages = {
  metadata: { title: 'JobTracker', description: 'Отслеживайте отклики и собеседования' },
  common: { save: 'Сохранить', cancel: 'Отмена', delete: 'Удалить', close: 'Закрыть', edit: 'Редактировать', create: 'Создать', loading: 'Загрузка…', tryAgain: 'Повторить', search: 'Поиск…', settings: 'Настройки', language: 'Язык', noResults: 'Ничего не найдено' },
  navigation: { dashboard: 'Главная', applications: 'Все отклики', findJobs: 'Найти вакансии', wishlist: 'Избранное', calendar: 'Календарь', companies: 'Компании', contacts: 'Контакты', notes: 'Заметки', reminders: 'Напоминания', notifications: 'Уведомления', statistics: 'Статистика', profile: 'Профиль', vacancies: 'Вакансии', candidates: 'Кандидаты', management: 'Управление', workspace: 'Рабочее пространство', analytics: 'Аналитика', settings: 'Настройки' },
  topbar: { profileSettings: 'Настройки профиля', settings: 'Настройки', logout: 'Выйти', notifications: 'Уведомления', avatar: 'Аватар' },
  public: { browseJobs: 'Смотреть вакансии', myApplications: 'Мои отклики', dashboard: 'Главная', signIn: 'Войти', signUp: 'Регистрация', browseTitle: 'Вакансии' },
  jobs: { search: 'Поиск вакансий…', location: 'Фильтр по местоположению…', searchButton: 'Найти', empty: 'Вакансии не найдены. Измените параметры поиска.', posted: 'Опубликовано {date}', previous: 'Назад', next: 'Вперёд', loadFailed: 'Не удалось загрузить вакансии', notAvailable: 'Нет данных' },
  vacancies: { active: 'Активные', archived: 'Архивные', search: 'Поиск по названию или компании', allStatuses: 'Все статусы', published: 'Опубликована', closed: 'Закрыта', noMatch: 'По выбранным фильтрам вакансий нет.', empty: 'Вакансий пока нет. Создайте первую вакансию.', created: 'Создано {date}', deleted: 'Вакансия удалена.', updated: 'Статус вакансии обновлён.', deleteFailed: 'Не удалось удалить вакансию.', updateFailed: 'Не удалось обновить статус.', loadFailed: 'Не удалось загрузить вакансии' },
  language: { label: 'Язык', description: 'Выберите язык интерфейса JobTracker.', detected: 'Изначально язык определяется из настроек браузера.', english: 'English', polish: 'Polski', russian: 'Русский', changed: 'Язык изменён', failed: 'Не удалось изменить язык' },
  documents: { securePreview: 'Защищённый просмотр документа', download: 'Скачать', open: 'Открыть документ в новой вкладке', close: 'Закрыть просмотр', unavailable: 'Предпросмотр недоступен', fallback: 'Оригинальный документ по-прежнему можно скачать.', loadFailed: 'Не удалось загрузить документ' },
  notifications: { loading: 'Загрузка уведомлений…', loadError: 'Ошибка загрузки уведомлений: {error}', all: 'Все', unread: 'Непрочитанные ({count})', read: 'Прочитанные', markAll: 'Отметить все прочитанными', noUnread: 'Нет непрочитанных уведомлений', empty: 'Нет уведомлений', emptyYet: 'Уведомлений пока нет', alreadyRead: 'Уже прочитано', markRead: 'Отметить прочитанным', delete: 'Удалить', viewAll: 'Все уведомления', title: 'Уведомления' },
  auth: { tagline: 'Следите за своим карьерным путем', join: 'Присоединяйтесь', welcome: 'С возвращением', signInAccount: 'Войдите в свой аккаунт', createAccount: 'Создать аккаунт', createYourAccount: 'Создайте аккаунт', terms: 'Входя в систему, вы соглашаетесь с Условиями использования', loginFailed: 'Не удалось войти', loginRetry: 'Не удалось войти. Попробуйте снова.', unexpected: 'Что-то пошло не так. Попробуйте снова.', signIn: 'Войти', email: 'Электронная почта', password: 'Пароль', noAccount: 'Нет аккаунта?', newHere: 'Впервые здесь?', alreadyAccount: 'Уже есть аккаунт?', register: 'Создать аккаунт', firstName: 'Имя', lastName: 'Фамилия', confirmPassword: 'Подтвердите пароль', back: 'Назад', who: 'Кто вы?', seeker: 'Соискатель', seekerDescription: 'Ищу новые возможности', recruiter: 'Рекрутер', recruiterDescription: 'Нанимаю талантливых людей', asRole: 'Роль: {role}', fillFields: 'Заполните все поля', passwordRequirements: 'Пароль не соответствует требованиям', passwordsMatch: 'Пароли совпадают', passwordsMismatch: 'Пароли не совпадают', atLeastEight: 'Не менее 8 символов', uppercase: 'Одна заглавная буква', lowercase: 'Одна строчная буква', number: 'Одна цифра', registrationFailed: 'Не удалось зарегистрироваться', registrationRetry: 'Не удалось зарегистрироваться. Попробуйте снова.' },
  pages: { settingsTitle: 'Настройки', settingsDescription: 'Управляйте настройками приложения.', profileTitle: 'Профиль', profileDescription: 'Управляйте аккаунтом и личной информацией', applicationsTitle: 'Мои отклики', applicationsDescription: 'Отслеживайте свои отклики на вакансии', companiesTitle: 'Компании', companiesDescription: 'Ведите личный список интересующих компаний.', contactsTitle: 'Контакты', contactsDescription: 'Управляйте контактами, полученными при поиске работы.', notesTitle: 'Заметки', notesDescription: 'Храните личные заметки, связанные с откликами.', remindersTitle: 'Напоминания', remindersDescription: 'Планируйте следующие шаги и важные сроки.', calendarTitle: 'Календарь', calendarDescription: 'Следите за собеседованиями и личными событиями', statisticsTitle: 'Статистика', vacanciesTitle: 'Вакансии', vacanciesDescription: 'Создавайте вакансии и управляйте ими', createVacancy: 'Создать вакансию', candidatesTitle: 'Кандидаты', candidatesDescription: 'Просматривайте кандидатов на свои вакансии', notificationsTitle: 'Уведомления', notificationsDescription: 'Следите за изменениями статусов откликов', wishlistTitle: 'Избранное', wishlistDescription: 'Сохранённые вакансии' }
};
export default ru;
